baseURL: http://resonate.coop/
languageCode: en-us
title: Resonate
menu:
  main:
  - identifier: about
    name: About
    title: About Resonate
    url: /about/
    weight: -110
  - identifier: pricing
    name: Pricing
    title: Resonate Pricing
    url: /pricing/
    weight: -109
  footer1:
  - identifier: manifesto
    name: Manifesto
    title: Resonate Manifesto
    url: /manifesto/
    weight: -107
  - identifier: about
    name: About
    title: About Resonate
    url: /about/
    weight: -106
  - identifier: pricing
    name: Pricing
    title: Resonate Pricing
    url: /pricing/
    weight: -105
  - identifier: editorial
    name: Editorial
    title: Resonate Editorial
    url: /editorial/
    weight: -104
  footer2:
  - identifier: press
    name: Press
    title: Resonate Press
    url: /press/
    weight: -103
  - identifier: team
    name: Team
    title: Resonate Team
    url: /team/
    weight: -102
  - identifier: coop
    name: Co-op
    title: We're a co-op
    url: /coop/
    weight: -101
  - identifier: contact
    name: Contact
    title: Contact Resonate
    url: /contact/
    weight: -100
  tge:
  - identifier: who
    name: who
    title: who
    url: /token-generation-event#who
    weight: -99
  - identifier: why
    name: why
    title: why
    url: /token-generation-event#why
    weight: -98
  - identifier: how
    name: how
    title: how
    url: /token-generation-event#how
    weight: -97
  - identifier: roadmap
    name: roadmap
    title: roadmap
    url: /token-generation-event#roadmap
    weight: -96
  - identifier: token
    name: token
    title: token
    url: /token-generation-event#token
    weight: -95
  - identifier: collborators
    name: collborators
    title: collborators
    url: /token-generation-event#collborators
    weight: -94
  - identifier: press
    name: press
    title: press
    url: /token-generation-event#press
    weight: -93
