title = "Resonate"
baseURL = "/"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
relativeurls = true
pygmentsUseClasses = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      title = "About Resonate"
      url = "/about/"
      weight = -111.0

      [[languages.en.menu.main]]
      identifier = "pricing"
      name = "Pricing"
      title = "Resonate Pricing"
      url = "/pricing/"
      weight = -110.0

      [[languages.en.menu.main]]
      identifier = "join"
      name = "Join"
      title = "Join us"
      url = "/join/"
      weight = -109.0

      [[languages.en.menu.footer1]]
      identifier = "manifesto"
      name = "Manifesto"
      title = "Resonate Manifesto"
      weight = -107.0

      [[languages.en.menu.footer1]]
      identifier = "about"
      name = "About"
      title = "About Resonate"
      url = "/about/"
      weight = -106.0

      [[languages.en.menu.footer1]]
      identifier = "pricing"
      name = "Pricing"
      title = "Resonate Pricing"
      url = "/pricing/"
      weight = -105.0

      [[languages.en.menu.footer1]]
      identifier = "editorial"
      name = "Editorial"
      title = "Resonate Editorial"
      url = "/editorial/"
      weight = -104.0

      [[languages.en.menu.footer2]]
      identifier = "press"
      name = "Press"
      title = "Resonate Press"
      url = "/press/"
      weight = -103.0

      [[languages.en.menu.footer2]]
      identifier = "team"
      name = "Team"
      title = "Resonate Team"
      url = "/team/"
      weight = -102.0

      [[languages.en.menu.footer2]]
      identifier = "coop"
      name = "Co-op"
      title = "We're a co-op"
      url = "/coop/"
      weight = -101.0

      [[languages.en.menu.footer2]]
      identifier = "contact"
      name = "Contact"
      title = "Contact Resonate"
      url = "/contact/"
      weight = -100.0

      [[languages.en.menu.about]]
      identifier = "who"
      name = "who"
      title = "who"
      url = "#who"
      weight = -99.0

      [[languages.en.menu.about]]
      identifier = "why"
      name = "why"
      title = "why"
      url = "#why"
      weight = -98.0

      [[languages.en.menu.about]]
      identifier = "how"
      name = "how"
      title = "how"
      url = "#how"
      weight = -97.0

      [[languages.en.menu.about]]
      identifier = "roadmap"
      name = "roadmap"
      title = "roadmap"
      url = "#roadmap"
      weight = -95.0

      [[languages.en.menu.growthcampaign]]
      identifier = "who"
      name = "who"
      title = "who"
      url = "#who"
      weight = -99.0

      [[languages.en.menu.growthcampaign]]
      identifier = "why"
      name = "why"
      title = "why"
      url = "#why"
      weight = -98.0

      [[languages.en.menu.growthcampaign]]
      identifier = "how"
      name = "how"
      title = "how"
      url = "#how"
      weight = -97.0

      [[languages.en.menu.growthcampaign]]
      identifier = "journey"
      name = "journey"
      title = "journey"
      url = "#journey"
      weight = -96.0

      [[languages.en.menu.growthcampaign]]
      identifier = "roadmap"
      name = "roadmap"
      title = "roadmap"
      url = "#roadmap"
      weight = -95.0

      [[languages.en.menu.growthcampaign]]
      identifier = "collaborators"
      name = "collaborators"
      title = "collaborators"
      url = "#collaborators"
      weight = -94.0

      [[languages.en.menu.growthcampaign]]
      identifier = "press"
      name = "press"
      title = "press"
      url = "#press"
      weight = -93.0
    
  [languages.fr]
    weight = 2
    languageName = "Français"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
      name = "A propos"
      title = "A propos de Resonate"
      url = "/fr/about/"
      weight = -111.0
      [[languages.fr.menu.main]]
      name = "Prix"
      title = "Resonate Pricing"
      url = "/fr/pricing/"
      weight = -110.0
      [[languages.fr.menu.main]]
      name = "Inscription"
      title = "S'inscrire"
      url = "/fr/join/"
      weight = -109.0

  [languages.es]
    weight = 3
    languageName = "Español"
    [languages.es.menu]
      [[languages.es.menu.main]]
      name = "Sobre"
      title = "Acerca de Resonate"
      url = "/es/about/"
      weight = -111.0
      [[languages.es.menu.main]]
      name = "Precios"
      title = "Precios de Resonate"
      url = "/es/pricing/"
      weight = -110.0
      [[languages.es.menu.main]]
      name = "Registro"
      title = "Regístrate ahora"
      url = "/es/join/"
      weight = -109.0

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  body_classes = "color-scheme--light sans-serif"
  description = "Resonate"
  legal = "Resonate Coop"
