title = "Resonate"
baseURL = "/"
languageCode = "en-us"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
relativeurls = true
pygmentsUseClasses = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  body_classes = "color-scheme--light sans-serif"
  description = "Resonate"
  legal = "Resonate Coop"

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  title = "About Resonate"
  url = "/about/"
  weight = -110.0

  [[menu.main]]
  identifier = "pricing"
  name = "Pricing"
  title = "Resonate Pricing"
  url = "/pricing/"
  weight = -109.0

  [[menu.footer1]]
  identifier = "manifesto"
  name = "Manifesto"
  title = "Resonate Manifesto"
  weight = -107.0

  [[menu.footer1]]
  identifier = "about"
  name = "About"
  title = "About Resonate"
  url = "/about/"
  weight = -106.0

  [[menu.footer1]]
  identifier = "pricing"
  name = "Pricing"
  title = "Resonate Pricing"
  url = "/pricing/"
  weight = -105.0

  [[menu.footer1]]
  identifier = "editorial"
  name = "Editorial"
  title = "Resonate Editorial"
  url = "/editorial/"
  weight = -104.0

  [[menu.footer2]]
  identifier = "press"
  name = "Press"
  title = "Resonate Press"
  url = "/press/"
  weight = -103.0

  [[menu.footer2]]
  identifier = "team"
  name = "Team"
  title = "Resonate Team"
  url = "/team/"
  weight = -102.0

  [[menu.footer2]]
  identifier = "coop"
  name = "Co-op"
  title = "We're a co-op"
  url = "/coop/"
  weight = -101.0

  [[menu.footer2]]
  identifier = "contact"
  name = "Contact"
  title = "Contact Resonate"
  url = "/contact/"
  weight = -100.0

  [[menu.about]]
  identifier = "who"
  name = "who"
  title = "who"
  url = "#who"
  weight = -99.0

  [[menu.about]]
  identifier = "why"
  name = "why"
  title = "why"
  url = "#why"
  weight = -98.0

  [[menu.about]]
  identifier = "how"
  name = "how"
  title = "how"
  url = "#how"
  weight = -97.0

  [[menu.about]]
  identifier = "roadmap"
  name = "roadmap"
  title = "roadmap"
  url = "#roadmap"
  weight = -95.0
