title: Resonate
baseURL: /
languageCode: en-us
DefaultContentLanguage: en
Paginate: 10
googleAnalytics: ''
enableRobotsTXT: true
relativeurls: true
removePathAccents: true
pygmentsUseClasses: true
metaDataFormat: yaml
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
languages:
  en:
    weight: 1
    languageName: English
    menu:
      main:
      - identifier: about
        name: About
        title: About Resonate
        url: /about/
        weight: -111
      - identifier: stream2own
        name: Pricing
        title: Resonate Pricing
        url: /pricing/
        weight: -110
      - identifier: the-coop
        name: The Co-op
        title: The Co-op
        url: /the-coop/
        weight: -109
      - identifier: blog
        name: Blog
        title: Resonate Blog
        url: /blog/
        weight: -108
      - identifier: handbook
        name: Handbook
        title: Handbook
        url: https://community.resonate.is/c/handbook/60
        weight: -107
      - identifier: forum
        name: Forum
        title: Forum
        url: https://community.resonate.is/
        weight: -106
      footer1:
      - identifier: about
        name: About
        title: About Resonate
        url: /about/
        weight: -111
      - identifier: stream2own
        name: Pricing
        title: Resonate Pricing
        url: /stream2own/
        weight: 1
      - identifier: the-coop
        name: The Co-op
        title: The Co-op
        url: /the-coop/
        weight: 2
      - identifier: blog
        name: Blog
        title: Resonate Blog
        url: /blog/
        weight: 3
      - identifier: handbook
        name: Handbook
        title: Handbook
        url: https://community.resonate.is/c/handbook/60
        weight: 4
      footer2:
      - identifier: join
        name: Join
        title: Join Resonate
        url: /join/
        weight: 1
      - identifier: volunteering
        name: Volunteering
        title: Volunteering
        url: /volunteering/
        weight: 2
      - identifier: team
        name: Team
        title: Resonate Team
        url: /team/
        weight: 3
      - identifier: forum
        name: Forum
        title: Forum
        url: https://community.resonate.is/
        weight: 4
      footer3:
      - identifier: blog
        name: Blog
        title: Resonate Blog
        url: /blog/
        weight: 2
      - identifier: newsletter
        name: Newsletter
        title: Resonate Newsletter
        url: /newsletter/
        weight: 3
      - identifier: contact
        name: Contact
        title: Contact
        url: /contact/
        weight: 4
      footer4:
      - identifier: documentation
        name: Documentation
        title: Documentation
        url: /documentation/
        weight: 1
      - identifier: github
        name: GitHub
        title: Resonate GitHub
        url: https://github.com/resonatecoop/
        weight: 2
      - identifier: report
        name: Report a problem
        title: Report a problem
        url: https://github.com/resonatecoop/
        weight: 3
      - identifier: donate
        name: Donate
        title: Donate
        url: https://opencollective.com/resonate
        weight: 4
      footer:
      - identifier: terms
        name: Terms + Conditions
        title: Documentation
        url: /terms/
        weight: 2
      - identifier: privacy
        name: Privacy Policy
        title: Privacy Policy
        url: /privacy-policy/
        weight: 3
  fr:
    weight: 2
    languageName: Français
    menu:
      main:
      - identifier: a-propos
        name: À propos
        title: À propos de Resonate
        url: /a-propos/
        weight: -111
      - identifier: stream2own
        name: Tarifs
        title: Tarifs de Resonate
        url: /stream2own/
        weight: -110
      - identifier: la-coop
        name: La Coop
        title: La Coop
        url: /la-coop/
        weight: -109
      - identifier: blog
        name: Blog
        title: Blog de Resonate
        url: /blog/
        weight: -108
      - identifier: handbook
        name: Handbook
        title: Resonate Handbook
        url: https://community.resonate.is/c/handbook/60
        weight: -107
      - identifier: forum
        name: Forum
        title: Resonate Community Forum
        url: https://community.resonate.is/
        weight: -106
  es:
    weight: 3
    languageName: Español
    menu:
      main:
      - identifier: sobre
        name: Sobre
        title: Sobre Resonate
        url: /a-propos/
        weight: -111
      - identifier: stream2own
        name: Principio 
        title: Principio de Resonate
        url: /stream2own/
        weight: -110
      - identifier: la-coop
        name: La Coop
        title: La Coop
        url: /la-coop/
        weight: -109
      - identifier: blog
        name: Blog
        title: Resonate blog 
        url: /blog/
        weight: -108
      - identifier: handbook
        name: Handbook
        title: Resonate Handbook
        url: https://community.resonate.is/c/handbook/60
        weight: -107
      - identifier: forum
        name: Forum
        title: Resonate Community Forum
        url: https://community.resonate.is/
        weight: -106
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  body_classes: color-scheme--light sans-serif
  description: Play fair.
  legal: Resonate
  social:
  - name: fb
    title: Facebook
    url: https://www.facebook.com/resonatecoop
  - name: tw
    title: Twitter
    url: https://twitter.com/resonatecoop
  - name: ig
    title: Instagram
    url: https://www.instagram.com/resonate_coop/
  - name: rss
    title: Blog RSS feed
    url: /blog/index.xml
